spring:
  application:
    name: testkotlin
  data:
    dynamodb:
      entity2ddl:
        auto: create-drop

amazon:
  dynamodb:
    endpoint: http://localhost:8000
  aws:
    accesskey: empty
    secretkey: empty
