package com.testprojectkotlin.model.entity

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable

@DynamoDBTable(tableName = "client")
data class Client (
    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    @DynamoDBAttribute(attributeName = "id")
    var id: String? = null,

    @DynamoDBAttribute(attributeName = "first_name")
    var firstName: String,

    @DynamoDBAttribute(attributeName = "last_name")
    var lastName: String,

    @DynamoDBAttribute(attributeName = "email")
    var email: String,

    @DynamoDBAttribute(attributeName = "job")
    var job: String? = null,

    @DynamoDBAttribute(attributeName = "position")
    var position: String? = null,

    @DynamoDBAttribute(attributeName = "gender")
    var gender: String? = null
) {
    constructor() : this(null, "", "", "", null, null, null)
}