package com.testprojectkotlin.model.entity

//import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute
//import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey
//import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey
//import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable
import jakarta.persistence.Entity
import jakarta.persistence.GeneratedValue
import jakarta.persistence.Id
import jakarta.persistence.Table
import lombok.*
import java.util.*

//@DynamoDBTable(tableName = "client")
@Data
@EqualsAndHashCode
@NoArgsConstructor
@AllArgsConstructor
@Entity
@Table(name = "client")
@Builder
data class Client (
//    @Id
//    @GeneratedValue(strategy = GenerationType.UUID)
//    @DynamoDBHashKey
//    @DynamoDBAutoGeneratedKey
//    var id: UUID? = null,
//
//    @DynamoDBAttribute(attributeName = "first_name")
//    var firstName: String,
//
//    @DynamoDBAttribute(attributeName = "last_name")
//    var lastName: String,
//
//    @DynamoDBAttribute(attributeName = "email")
//    var email: String,
//
//    @DynamoDBAttribute(attributeName = "job")
//    var job: String? = null,
//
//    @DynamoDBAttribute(attributeName = "position")
//    var position: String? = null

    @Id
    @GeneratedValue
    var id: UUID? = null,

    var firstName: String,

    var lastName: String,

    var email: String,

    var gender: String? = null,

    var job: String? = null,

    var position: String? = null
)